version: '3.8'

services:
  webar-app:
    build: .
    container_name: fga-solar-calc
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development